### ISSUE TITLE
[BUG]: The Pull request within the fork has failed.

### ISSUE THREAD

**Issue by bqdcc** [OneKeyHQ/app-monorepo#3485]
When I try to run a pull request coming from a fork #3484 , checks `bundlediff-ios / Build ios head (pull_request)` and `bundlediff-web / Build web head (pull_request)`, I get this error instead(Fetching the repository):
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/fix/wallet_selector_trigger*:refs/remotes/origin/fix/wallet_selector_trigger* +refs/tags/fix/wallet_selector_trigger*:refs/tags/fix/wallet_selector_trigger*
  Error: The process '/usr/bin/git' failed with exit code 1
```
Working:

- If the branch comes from the main repository.

Not working:

- If the branch comes from the fork.

**Comment by bqdcc** [comment]
I know how to make it work now.
```yml
# .github/workflows/bundlediff-web.yml
build-web-head:
    name: 'Build web head'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          # Add a line below
          repository: ${{github.event.pull_request.head.repo.full_name}} 
```
I'm using another account for testing, and this is working.

**Comment by bqdcc** [comment]
A new issue has arisen. When the workflow reaches 'Compare base & head bundle sizes', it needs to acquire the 'GITHUB_TOKEN,' but forked pull requests don't have the permissions to do so.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events

The permissions remain as 'read-only.
```
GITHUB_TOKEN Permissions
  Actions: read
  Checks: read
  Contents: read
  Deployments: read
  Discussions: read
  Issues: read
  Metadata: read
  Packages: read
  Pages: read
  PullRequests: read
  RepositoryProjects: read
  SecurityEvents: read
  Statuses: read
```
The error message is as follows:
```
Error: Resource not accessible by integration
```
Perhaps we can use pull_request_target to obtain higher permissions.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

However, considering security concerns, it is advisable to skip the 'Compare base & head bundle sizes' step for forked pull requests.
```yml
# .github/workflows/bundlediff-web.yml
compare:
    # Add a line below
    if: github.event.pull_request.head.repo.fork == false
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-web-base, build-web-head]
    ...
```
